apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  project: default
  sources:
  - repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.3.7
    helm:
      releaseName: kyverno
      values: |
        crds:
          annotations:
            argocd.argoproj.io/sync-options: Replace=true
          # migration:
          #   enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
