replicaCount: 2

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: false

readinessProbe:
  enabled: true
  httpGet: { path: "/", port: http }
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  enabled: true
  httpGet: { path: "/", port: http }
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits:   { cpu: 200m, memory: 256Mi }
